name: Staging Playwright Tests
on:
  # push:
  #   branches: [ main, staging ]
  # pull_request:
  #   branches: [ main, staging ]
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Select test suite to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - smoke

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: staging
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: |
        if [ "${{ github.event.inputs.test_type }}" == "smoke" ]; then
          npx playwright test --grep "@smoke" --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --reporter=blob
        else
          npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --reporter=blob
        fi
      env:
        ENV: staging
        BASE_URL: ${{ secrets.BASE_URL }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}

    - name: Upload Report Shard
      uses: actions/upload-artifact@v6
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-staging-${{ matrix.shardIndex }}
        path: blob-report/
        retention-days: 1

  merge-reports:
    if: ${{ !cancelled() }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Download all shards
      uses: actions/download-artifact@v7
      with:
        path: all-shards
        pattern: playwright-report-staging-*
        merge-multiple: true

    - name: Merge reports
      run: npx playwright merge-reports --reporter html ./all-shards

    - name: Upload consolidated report
      uses: actions/upload-artifact@v6
      with:
        name: playwright-report-staging-final
        path: playwright-report/
        retention-days: 1
